# Data Wrangling – Consigna práctica

Dataset: ventas_desordenadas_sucias.csv

## 1. Cargar datos

In [11]:
import pandas as pd

path = 'data/ventas_sucias_500_registros.csv'
df = pd.read_csv(path)
df.head()

        fecha     monto producto region vendedor         canal
0  2023-07-17   35849.0   Laptop  Norte      NaN  Distribuidor
1  2022-07-21   91813.0  Monitor  Norte      Ana        Tienda
2  2022-06-30  129059.0   Laptop    Sur     Luis        Online
3  2022-12-14  126446.0  Monitor    NaN     Juan        Online
4  2023-10-09   34971.0  Monitor    NaN    Pedro        Online

## 2. Conversión de tipos (fecha y monto)

In [12]:
# Fecha
df['fecha'] = pd.to_datetime(df['fecha'], errors='coerce')

# Monto
monto = df['monto'].astype(str)
monto = monto.str.replace('$','', regex=False)
monto = monto.str.replace('.', '', regex=False)
monto = monto.str.replace(',', '.', regex=False)
df['monto'] = pd.to_numeric(monto, errors='coerce')

df.dtypes

fecha       datetime64[ns]
monto                int64
producto            object
region              object
vendedor            object
canal               object
dtype: object

## 3. Reemplazar valores vacíos

In [13]:
df = df.fillna('Desconocido')
df.head()

       fecha    monto producto       region     vendedor         canal
0 2023-07-17   358490   Laptop        Norte  Desconocido  Distribuidor
1 2022-07-21   918130  Monitor        Norte          Ana        Tienda
2 2022-06-30  1290590   Laptop          Sur         Luis        Online
3 2022-12-14  1264460  Monitor  Desconocido         Juan        Online
4 2023-10-09   349710  Monitor  Desconocido        Pedro        Online

## 4. Crear categoría según monto

In [15]:
def categoria_monto(x):
    try:
        x = float(x)
        if x < 500:
            return 'Bajo'
        elif x < 2000:
            return 'Medio'
        else:
            return 'Alto'
    except:
        return 'Desconocido'

df['CategoriaMonto'] = df['monto'].apply(categoria_monto)
df[['monto','CategoriaMonto']].head()

     monto CategoriaMonto
0   358490           Alto
1   918130           Alto
2  1290590           Alto
3  1264460           Alto
4   349710           Alto

## 5. Ordenar por fecha y monto

In [16]:
df = df.sort_values(by=['fecha','monto'])
df.head()

,fecha,monto,producto,region,vendedor,canal,CategoriaMonto
56,2022-01-02,372120,Monitor,Centro,Pedro,Distribuidor,Alto
456,2022-01-02,445940,Teclado,Sur,Pedro,Distribuidor,Alto
186,2022-01-05,1303260,Laptop,Centro,María,Online,Alto
108,2022-01-09,1350420,Monitor,Centro,Desconocido,Tienda,Alto
107,2022-01-12,953280,Laptop,Norte,Pedro,Online,Alto

## 6. Renombrar columnas

In [17]:
df = df.rename(columns={
    'VentaID':'ID_Venta',
    'fecha':'Fecha',
    'Cliente':'ClienteNombre',
    'Producto':'ProductoNombre',
    'Cantidad':'CantidadVendida',
    'monto':'Monto',
    'Region':'RegionVenta'
})

df.head()

,Fecha,Monto,producto,region,vendedor,canal,CategoriaMonto
56,2022-01-02,372120,Monitor,Centro,Pedro,Distribuidor,Alto
456,2022-01-02,445940,Teclado,Sur,Pedro,Distribuidor,Alto
186,2022-01-05,1303260,Laptop,Centro,María,Online,Alto
108,2022-01-09,1350420,Monitor,Centro,Desconocido,Tienda,Alto
107,2022-01-12,953280,Laptop,Norte,Pedro,Online,Alto

## Dataset final listo para análisis