<h2>Parte 1</h2>

<h3>Ejemplo de muestreo aleatorio en Pandas</h3>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('data/Titanic-Dataset.csv')
df.head()

In [ ]:

# Obtener una muestra aleatoria de 10 filas
df_muestra = df.sample(n=10, random_state=42)
df_muestra

<h3>Permutación aleatoria de datos</h3>

In [ ]:
# Reordenar aleatoriamente todas las filas
df_permutado = df.sample(frac=1, random_state=42)
df_permutado

In [ ]:
df_permutado.shape

<h3>Ejemplo de ordenamiento por una columna</h3>

In [ ]:
df.head()

In [ ]:
# Ordenar por la columna 'PassengerId' de forma ascendente
df_ordenado = df.sort_values(by='Pclass', ascending=False)
df_ordenado.head(10)

<h3>Ordenamiento por múltiples columnas</h3>

In [ ]:
# Ordenar primero por 'PassengerId' (ascendente) y luego por 'Pclass' (descendente)
df_ordenado = df.sort_values(by=['Pclass','PassengerId'], ascending=[False, True])
df_ordenado.head()

<h3>Ejemplo de detección de duplicados</h3>

In [ ]:
# Identificar registros duplicados
duplicados = df.duplicated()
duplicados.sum()  # Número de registros duplicados

<h3>Eliminación de duplicados</h3>

In [ ]:
df.shape

In [ ]:
# Eliminar registros duplicados
df_sin_duplicados = df.drop_duplicates()
df_sin_duplicados.shape

<h3>Ejemplo de reemplazo de valores</h3>

In [ ]:
# Crear un DataFrame con valores erróneos
df2 = pd.DataFrame({'Producto': ['Laptop', 'Tablet', 'Celular', 'Lapto', 'Tablet'],
                   'Precio': [1000, 500, 800, 950, 520]})

In [ ]:
df2

In [ ]:
# Reemplazar valores incorrectos
df2['Producto'] = df2['Producto'].replace({'Lapto': 'Laptop'})
df2

<h3>Reemplazo con expresiones regulares</h3>

In [ ]:
# Reemplazar valores que contengan un patrón específico
df2['Producto'] = df2['Producto'].str.replace(r'Lapto', 'Laptop', regex=True)
df2

<h3>Ejemplo de binning en Pandas</h3>

In [ ]:
# Crear un DataFrame con datos continuos
df3 = pd.DataFrame({'Edad': [22, 25, 30, 35, 40, 45, 50, 55, 60]})
df3

In [ ]:
# Definir los rangos (bins)
bins = [20, 30, 40, 50, 60]
etiquetas = ['Joven', 'Adulto Joven', 'Adulto', 'Mayor']

In [ ]:
# Aplicar discretización
df3['Grupo Etario'] = pd.cut(df3['Edad'], bins=bins, labels=etiquetas)
df3

<h3>Ejemplo de uso de .map() en una columna categórica</h3>

In [ ]:
import pandas as pd

# Crear un DataFrame
df4 = pd.DataFrame({'Producto': ['Laptop', 'Tablet', 'Celular'],
                   'Categoría': ['Electrónica', 'Electrónica', 'Comunicación']})
df4

In [ ]:
df4.dtypes

In [ ]:
# Crear un diccionario de mapeo
mapeo = {'Electrónica': 'Tecnología', 'Comunicación': 'Telecomunicaciones'}

In [ ]:
# Aplicar mapeo
df4['Nueva Categoría'] = df4['Categoría'].map(mapeo)
df4

<p>.map() en Pandas se utiliza para transformar los valores de una columna (Series) basándose en una correspondencia específica</p>

<h3>Ejemplo de .apply() en múltiples columnas</h3>

In [ ]:
# Crear un DataFrame
df5 = pd.DataFrame({'Nombre': ['Ana', 'Luis', 'Carlos'],
                   'Edad': [25, 30, 28],
                   'Salario': [50000, 54000, 58000]})
df5

In [ ]:
# Aplicar una función a varias columnas
def categorizar_fila(fila):
    if fila['Salario'] > 55000:
        return 'Alto'
    else:
        return 'Medio'

In [ ]:
# Aplicar función a cada fila
df5['Nivel Salarial'] = df5.apply(categorizar_fila, axis=1)
df5

<h3>Ejemplo de expresión lambda para calcular descuentos</h3>

In [ ]:
# Crear un DataFrame
df6 = pd.DataFrame({'Precio': [1000, 500, 800, 1500]})
df6

In [ ]:
# Aplicar descuento del 10%
df6['Precio con Descuento'] = df6['Precio'].apply(lambda x: x * 0.80)
df6

<h2>Parte 2</h2>

<h3>Ejemplo de agregar una nueva columna</h3>

In [9]:
import pandas as pd

# Crear un DataFrame
df = pd.DataFrame({'Nombre': ['Ana', 'Luis', 'Carlos'],
                   'Edad': [25, 30, 28]})
df

   Nombre  Edad
0     Ana    25
1    Luis    30
2  Carlos    28

In [10]:
# Agregar una nueva columna
df['Ciudad'] = ['Madrid', 'Barcelona', 'Sevilla']
df

   Nombre  Edad     Ciudad
0     Ana    25     Madrid
1    Luis    30  Barcelona
2  Carlos    28    Sevilla

<h3>Ejemplo de eliminar una columna</h3>

In [ ]:
df

In [ ]:
# Eliminar la columna 'Ciudad'
df2 = df.drop(columns=['Nombre'])
df2

<h3>Ejemplo de selección de un subconjunto de columnas</h3>

In [11]:
df

   Nombre  Edad     Ciudad
0     Ana    25     Madrid
1    Luis    30  Barcelona
2  Carlos    28    Sevilla

In [12]:
# Seleccionar solo las columnas 'Nombre' y 'Edad'
df_reducido = df[['Edad', 'Ciudad']]
df_reducido

   Edad     Ciudad
0    25     Madrid
1    30  Barcelona
2    28    Sevilla

<h3>Ejemplo de selección de filas específicas</h3>

In [13]:
df

   Nombre  Edad     Ciudad
0     Ana    25     Madrid
1    Luis    30  Barcelona
2  Carlos    28    Sevilla

In [14]:
# Seleccionar las primeras dos filas
df_subset = df.iloc[:2]
df_subset

  Nombre  Edad     Ciudad
0    Ana    25     Madrid
1   Luis    30  Barcelona

<h3>Ejemplo de conversión de tipos</h3>

In [15]:
# Crear un DataFrame con datos en formato de texto
df = pd.DataFrame({'ID': ['1', '2', '3'], 'Precio': ['1000', '500', '800']})
df

  ID Precio
0  1   1000
1  2    500
2  3    800

In [16]:
df.dtypes

ID        object
Precio    object
dtype: object

In [17]:
# Convertir a tipos numéricos
df['ID'] = df['ID'].astype(int)
df['Precio'] = df['Precio'].astype(float)
df.dtypes

ID          int64
Precio    float64
dtype: object

<h3>Ejemplo de definición de índice</h3>

In [18]:
df

   ID  Precio
0   1  1000.0
1   2   500.0
2   3   800.0

In [20]:
df.index.name

In [21]:
# Definir la columna 'ID' como índice
df.set_index('ID', inplace=True)
df

    Precio
ID
1   1000.0
2    500.0
3    800.0

In [22]:
df.index.name

'ID'

<h3>Ejemplo de reseteo de índice</h3>

In [23]:
# Resetear el índice
df.reset_index(inplace=True)
df

   ID  Precio
0   1  1000.0
1   2   500.0
2   3   800.0

In [24]:
df.index.name

<h3>Ejemplo de renombrar columnas</h3>

In [25]:
df

   ID  Precio
0   1  1000.0
1   2   500.0
2   3   800.0

In [26]:
# Renombrar columnas
df = df.rename(columns={'Precio': 'Costo'})
df

   ID   Costo
0   1  1000.0
1   2   500.0
2   3   800.0

<h3>Ejemplo de eliminación de duplicados</h3>

In [27]:
# Crear un DataFrame con datos duplicados
df = pd.DataFrame({'Nombre': ['Ana', 'Luis', 'Ana', 'Carlos'],
                   'Edad': [25, 30, 25, 28]})
df

   Nombre  Edad
0     Ana    25
1    Luis    30
2     Ana    25
3  Carlos    28

In [29]:
df.duplicated().sum()

np.int64(1)

In [30]:
# Eliminar duplicados
df_sin_duplicados = df.drop_duplicates()
df_sin_duplicados

   Nombre  Edad
0     Ana    25
1    Luis    30
3  Carlos    28