<h2>Parte 1</h2>

<h3>Ejemplo de muestreo aleatorio en Pandas</h3>

In [52]:
import pandas as pd
import numpy as np

In [53]:
df = pd.read_csv('data/Titanic-Dataset.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [54]:

# Obtener una muestra aleatoria de 10 filas
df_muestra = df.sample(n=10, random_state=42)
df_muestra

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
709,710,1,3,"Moubarek, Master. Halim Gonios (""William George"")",male,NaN,1,1,2661,15.2458,NaN,C
439,440,0,2,"Kvillner, Mr. Johan Henrik Johannesson",male,31.0,0,0,C.A. 18723,10.5000,NaN,S
840,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.0,0,1,248727,33.0000,NaN,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,NaN,C
290,291,1,1,"Barber, Miss. Ellen ""Nellie""",female,26.0,0,0,19877,78.8500,NaN,S
300,301,1,3,"Kelly, Miss. Anna Katherine ""Annie Kate""",female,NaN,0,0,9234,7.7500,NaN,Q
333,334,0,3,"Vander Planke, Mr. Leo Edmondus",male,16.0,2,0,345764,18.0000,NaN,S
208,209,1,3,"Carr, Miss. Helen ""Ellen""",female,16.0,0,0,367231,7.7500,NaN,Q
136,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.0,0,2,11752,26.2833,D47,S

<h3>Permutación aleatoria de datos</h3>

In [55]:
# Reordenar aleatoriamente todas las filas
df_permutado = df.sample(frac=1, random_state=42)
df_permutado.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
709,710,1,3,"Moubarek, Master. Halim Gonios (""William George"")",male,NaN,1,1,2661,15.2458,NaN,C
439,440,0,2,"Kvillner, Mr. Johan Henrik Johannesson",male,31.0,0,0,C.A. 18723,10.5000,NaN,S
840,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.0,0,1,248727,33.0000,NaN,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,NaN,C

In [56]:
df_permutado.shape

(891, 12)

<h3>Ejemplo de ordenamiento por una columna</h3>

In [57]:
# Ordenar por la columna 'PassengerId' de forma ascendente
df_ordenado = df.sort_values(by='PassengerId', ascending=True)
df_ordenado.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

<h3>Ordenamiento por múltiples columnas</h3>

In [58]:
# Ordenar primero por 'PassengerId' (ascendente) y luego por 'Pclass' (descendente)
df_ordenado = df.sort_values(by=['Pclass','PassengerId'], ascending=[True, False])
df_ordenado.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S

<h3>Ejemplo de detección de duplicados</h3>

In [59]:
# Identificar registros duplicados
duplicados = df.duplicated()
duplicados.sum()  # Número de registros duplicados

np.int64(0)

<h3>Eliminación de duplicados</h3>

In [60]:
df.shape

(891, 12)

In [61]:
# Eliminar registros duplicados
df_sin_duplicados = df.drop_duplicates()
df_sin_duplicados.shape

(891, 12)

<h3>Ejemplo de reemplazo de valores</h3>

In [62]:
# Crear un DataFrame con valores erróneos
df2 = pd.DataFrame({'Producto': ['Laptop', 'Tablet', 'Celular', 'Lapto', 'Tablet'],
                   'Precio': [1000, 500, 800, 950, 520]})

In [63]:
df2

  Producto  Precio
0   Laptop    1000
1   Tablet     500
2  Celular     800
3    Lapto     950
4   Tablet     520

In [64]:
# Reemplazar valores incorrectos
df2['Producto'] = df2['Producto'].replace({'Lapto': 'Laptop'})
df2

  Producto  Precio
0   Laptop    1000
1   Tablet     500
2  Celular     800
3   Laptop     950
4   Tablet     520

<h3>Reemplazo con expresiones regulares</h3>

In [65]:
# Reemplazar valores que contengan un patrón específico
df2['Producto'] = df2['Producto'].str.replace(r'Lapto', 'Laptop', regex=True)
df2

  Producto  Precio
0  Laptopp    1000
1   Tablet     500
2  Celular     800
3  Laptopp     950
4   Tablet     520

<h3>Ejemplo de binning en Pandas</h3>

In [66]:
# Crear un DataFrame con datos continuos
df3 = pd.DataFrame({'Edad': [22, 25, 30, 35, 40, 45, 50, 55, 60]})
df3

   Edad
0    22
1    25
2    30
3    35
4    40
5    45
6    50
7    55
8    60

In [67]:
# Definir los rangos (bins)
bins = [20, 30, 40, 50, 60]
etiquetas = ['Joven', 'Adulto Joven', 'Adulto', 'Mayor']

In [68]:
# Aplicar discretización
df3['Grupo Edad'] = pd.cut(df3['Edad'], bins=bins, labels=etiquetas)
df3

   Edad    Grupo Edad
0    22         Joven
1    25         Joven
2    30         Joven
3    35  Adulto Joven
4    40  Adulto Joven
5    45        Adulto
6    50        Adulto
7    55         Mayor
8    60         Mayor

<h3>Ejemplo de uso de .map() en una columna categórica</h3>

In [69]:
import pandas as pd

# Crear un DataFrame
df4 = pd.DataFrame({'Producto': ['Laptop', 'Tablet', 'Celular'],
                   'Categoría': ['Electrónica', 'Electrónica', 'Comunicación']})
df4

  Producto     Categoría
0   Laptop   Electrónica
1   Tablet   Electrónica
2  Celular  Comunicación

In [70]:
# Crear un diccionario de mapeo
mapeo = {'Electrónica': 'Tecnología', 'Comunicación': 'Telecomunicaciones'}

In [71]:
# Aplicar mapeo
df4['Nueva Categoría'] = df4['Categoría'].map(mapeo)
df4

  Producto     Categoría     Nueva Categoría
0   Laptop   Electrónica          Tecnología
1   Tablet   Electrónica          Tecnología
2  Celular  Comunicación  Telecomunicaciones

<p>.map() en Pandas se utiliza para transformar los valores de una columna (Series) basándose en una correspondencia específica</p>

<h3>Ejemplo de .apply() en múltiples columnas</h3>

In [72]:
# Crear un DataFrame
df5 = pd.DataFrame({'Nombre': ['Ana', 'Luis', 'Carlos'],
                   'Edad': [25, 30, 28],
                   'Salario': [50000, 54000, 58000]})
df5

   Nombre  Edad  Salario
0     Ana    25    50000
1    Luis    30    54000
2  Carlos    28    58000

In [73]:
# Aplicar una función a varias columnas
def categorizar_fila(fila):
    if fila['Salario'] > 50000:
        return 'Alto'
    else:
        return 'Medio'

In [74]:
# Aplicar función a cada fila
df5['Nivel Salarial'] = df5.apply(categorizar_fila, axis=1)
df5

   Nombre  Edad  Salario Nivel Salarial
0     Ana    25    50000          Medio
1    Luis    30    54000           Alto
2  Carlos    28    58000           Alto

<h3>Ejemplo de expresión lambda para calcular descuentos</h3>

In [75]:
# Crear un DataFrame
df6 = pd.DataFrame({'Precio': [1000, 500, 800, 1500]})
df6

   Precio
0    1000
1     500
2     800
3    1500

In [76]:
# Aplicar descuento del 10%
df6['Precio con Descuento'] = df6['Precio'].apply(lambda x: x * 0.90)
df6

   Precio  Precio con Descuento
0    1000                 900.0
1     500                 450.0
2     800                 720.0
3    1500                1350.0

<h2>Parte 2</h2>

<h3>Ejemplo de agregar una nueva columna</h3>

In [77]:
import pandas as pd

# Crear un DataFrame
df = pd.DataFrame({'Nombre': ['Ana', 'Luis', 'Carlos'],
                   'Edad': [25, 30, 28]})
df

   Nombre  Edad
0     Ana    25
1    Luis    30
2  Carlos    28

In [78]:
# Agregar una nueva columna
df['Ciudad'] = ['Madrid', 'Barcelona', 'Sevilla']
df

   Nombre  Edad     Ciudad
0     Ana    25     Madrid
1    Luis    30  Barcelona
2  Carlos    28    Sevilla

<h3>Ejemplo de eliminar una columna</h3>

In [79]:
# Eliminar la columna 'Ciudad'
df2 = df.drop(columns=['Ciudad'])
df2

   Nombre  Edad
0     Ana    25
1    Luis    30
2  Carlos    28

<h3>Ejemplo de selección de un subconjunto de columnas</h3>

In [80]:
df

   Nombre  Edad     Ciudad
0     Ana    25     Madrid
1    Luis    30  Barcelona
2  Carlos    28    Sevilla

In [81]:
# Seleccionar solo las columnas 'Nombre' y 'Edad'
df_reducido = df[['Edad', 'Ciudad']]
df_reducido

   Edad     Ciudad
0    25     Madrid
1    30  Barcelona
2    28    Sevilla

<h3>Ejemplo de selección de filas específicas</h3>

In [82]:
df

   Nombre  Edad     Ciudad
0     Ana    25     Madrid
1    Luis    30  Barcelona
2  Carlos    28    Sevilla

In [83]:
# Seleccionar las primeras dos filas
df_subset = df.iloc[:2]
df_subset

  Nombre  Edad     Ciudad
0    Ana    25     Madrid
1   Luis    30  Barcelona

<h3>Ejemplo de conversión de tipos</h3>

In [84]:
# Crear un DataFrame con datos en formato de texto
df = pd.DataFrame({'ID': ['1', '2', '3'], 'Precio': ['1000', '500', '800']})
df

  ID Precio
0  1   1000
1  2    500
2  3    800

In [85]:
df.dtypes

ID        object
Precio    object
dtype: object

In [86]:
# Convertir a tipos numéricos
df['ID'] = df['ID'].astype(int)
df['Precio'] = df['Precio'].astype(float)
df.dtypes

ID          int64
Precio    float64
dtype: object

<h3>Ejemplo de definición de índice</h3>

In [87]:
df

   ID  Precio
0   1  1000.0
1   2   500.0
2   3   800.0

In [88]:
# Definir la columna 'ID' como índice
df.set_index('ID', inplace=True)
df

    Precio
ID
1   1000.0
2    500.0
3    800.0

<h3>Ejemplo de reseteo de índice</h3>

In [89]:
# Resetear el índice
df.reset_index(inplace=True)
df

   ID  Precio
0   1  1000.0
1   2   500.0
2   3   800.0

<h3>Ejemplo de renombrar columnas</h3>

In [90]:
df

   ID  Precio
0   1  1000.0
1   2   500.0
2   3   800.0

In [91]:
# Renombrar columnas
df = df.rename(columns={'Costo': 'costo','ID':'id'})
df

   id  Precio
0   1  1000.0
1   2   500.0
2   3   800.0

<h3>Ejemplo de eliminación de duplicados</h3>

In [92]:
# Crear un DataFrame con datos duplicados
df = pd.DataFrame({'Nombre': ['Ana', 'Luis', 'Ana', 'Carlos'],
                   'Edad': [25, 30, 25, 28]})
df

   Nombre  Edad
0     Ana    25
1    Luis    30
2     Ana    25
3  Carlos    28

In [93]:
df.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [94]:
# Eliminar duplicados
df_sin_duplicados = df.drop_duplicates()
df_sin_duplicados

   Nombre  Edad
0     Ana    25
1    Luis    30
3  Carlos    28